# Generated by Django 4.2.5 on 2023-09-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=4)),
                ('time', models.IntegerField()),
                ('cost_per_person', models.IntegerField()),
                ('comment_count', models.IntegerField()),
            ],
        ),
    ]
